package com.ewida.skysense.util

object Constants {
    const val WEATHER_ICON_BASE_URL = "https://openweathermap.org/img/w/"
    const val ALERTS_NOTIFICATION_CHANNEL_ID = "ALERTS_NOTIFICATION_CHANNEL_ID"

    object SharedPreferences {
        const val SETTINGS_PREFERENCES_NAME = "APP_SETTINGS_PREFS"
        const val LANGUAGE_PREFERENCES_KEY = "LANGUAGE_PREFERENCES_KEY"
        const val UNIT_PREFERENCES_KEY = "UNIT_PREFERENCES_KEY"
        const val LOCATION_TYPE_PREFERENCES_KEY = "LOCATION_TYPE_PREFERENCES_KEY"
        const val MAP_LOCATION_LAT_PREFERENCES_KEY = "MAP_LOCATION_LAT_PREFERENCES_KEY"
        const val MAP_LOCATION_LONG_PREFERENCES_KEY = "MAP_LOCATION_LONG_PREFERENCES_KEY"
    }
}